django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("students.urls", namespace="students")),
]

students/urls.py
from django.urls import path
from . import views

app_name = "students"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:student_id>/", views.view_student, name="view_student"),
    path("add/", views.add, name="add"),
    path("edit/<int:student_id>/", views.edit, name="edit"),
    path("delete/<int:student_id>/", views.delete, name="delete"),
]

students/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    student_number = models.PositiveIntegerField()
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email_address = models.EmailField(max_length=100)
    field_of_study = models.CharField(max_length=50)
    gpa = models.FloatField()
    
    def __str__(self):
        return f"Student: {self.first_name} {self.last_name}"

students/forms.py
from django import forms
from .models import Student

class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            "student_number",
            "first_name",
            "last_name",
            "email_address",
            "field_of_study",
            "gpa",
        ]
        labels = {
            "student_number": "Student Number",
            "first_name": "First Name",
            "last_name": "Last Name",
            "email_address": "Email Address",
            "field_of_study": "Field of Study",
            "gpa": "GPA",
        }
        widgets = {
            "student_number": forms.NumberInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email_address": forms.EmailInput(attrs={"class": "form-control"}),
            "field_of_study": forms.TextInput(attrs={"class": "form-control"}),
            "gpa": forms.NumberInput(attrs={"class": "form-control"}),
        }

students/views.py
from django.shortcuts import render
from .models import Student
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .forms import StudentForm


# Create your views here.
def index(request):
    students = Student.objects.all()

    return render(
        request,
        "students/index.html",
        {
            "students": students,
        },
    )


def view_student(request, student_id):
    student = Student.objects.get(pk=student_id)
    return HttpResponseRedirect(reverse("students:index"))


def add(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            new_student_number = form.cleaned_data["student_number"]
            new_first_name = form.cleaned_data["first_name"]
            new_last_name = form.cleaned_data["last_name"]
            new_email_address = form.cleaned_data["email_address"]
            new_field_of_study = form.cleaned_data["field_of_study"]
            new_gpa = form.cleaned_data["gpa"]
            new_student = Student(
                student_number=new_student_number,
                first_name=new_first_name,
                last_name=new_last_name,
                email_address=new_email_address,
                field_of_study=new_field_of_study,
                gpa=new_gpa,
            )
            new_student.save()
            return render(
                request,
                "students/add.html",
                {
                    "form": form,
                    "success": True,
                },
            )

    else:
        form = StudentForm()
    return render(
        request,
        "students/add.html",
        {
            "form": form,
        },
    )
    
def edit(request, student_id):
    if request.method == "POST":
        student = Student.objects.get(pk=student_id)
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            form.save()
            return render(
                request,
                "students/edit.html",
                {
                    "form": form,
                    "success": True,
                },
            )
    else:
        student = Student.objects.get(pk=student_id)
        form = StudentForm(instance=student)
    return render(
        request,
        "students/edit.html",
        {
            "form": form,
        },
    )
    
def delete(request, student_id):
    if request.method == "POST":
        student = Student.objects.get(pk=student_id)
        student.delete()
    return HttpResponseRedirect(reverse("students:index"))
    

students/templates/students/add.html
{% extends "students/base.html" %}

{% block content %}
    <h3 class="text-center m-4">Add student</h3>
    {% if success %}
        <div class="alert alert-success" role="alert">
            The new student added successfully!
            <a href="{% url 'students:index' %}" class="alert-link">Go to Home Page.</a>
        </div>
    {% else %}
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card border-light mb-3">
                <div class="card-header"><i class="fa-solid fa-address-card fa-lg"></i>Student Registration</div>
                <div class="card-body">
                    <form action="{% url 'students:add' %}" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Add</button>
                        <a href="{% url 'students:index' %}" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
              </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

students/templates/students/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <title>Student Management System</title>
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
        />
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
        <body class="d-flex flex-column min-vh-100">
            <nav
                class="navbar navbar-expand-lg bg-primary"
                data-bs-theme="dark"
            >
                <div class="container-fluid">
                    <a class="navbar-brand" href="{% url 'students:index' %}"
                        ><i class="fa-solid fa-graduation-cap fa-lg"></i>Student
                        Management System</a
                    >
                    <button
                        class="navbar-toggler"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarColor01"
                        aria-controls="navbarColor01"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarColor01">
                        <ul class="navbar-nav me-auto">
                            
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'students:index' %}"
                                    ><i class="fa-solid fa-list fa-lg"></i>All
                                    Students</a
                                >
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'students:add' %}"
                                    ><i class="fa-solid fa-plus fa-lg"></i>Add
                                    Student</a
                                >
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <div class="container-fluid">
                {% block content %}
                {% endblock %}
            </div>
            <footer class="mt-auto mb-4">
                <div class="text-center">
                    <span>
                        CopyRight &copy;
                        <script>
                            document.write(new Date().getFullYear());
                        </script>
                        All rights reserved | This template is made with
                        <i class="fa fa-heart-o" aria-hidden="true"></i> by me
                    </span>
                </div>
            </footer>

            <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
        </body>
    </head>
</html>

students/templates/students/edit.html
{% extends "students/base.html" %}

{% block content %}
    <h3 class="text-center m-4">Update student</h3>
    {% if success %}
        <div class="alert alert-success" role="alert">
            The student has been updated successfully.
            <a href="{% url 'students:index' %}" class="alert-link">Go to Home Page.</a>
        </div>
    {% else %}
    <div class="row justify-content-center">
        <div class="col-6">
            <div class="card border-light mb-3">
                <div class="card-header"><i class="fa-solid fa-pen-to-square fa-lg"></i>Update Student Record</div>
                <div class="card-body">
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Update</button>
                        <a href="{% url 'students:index' %}" class="btn btn-secondary">Cancel</a>
                    </form>
                </div>
              </div>
        </div>
    </div>
    {% endif %}
{% endblock %}

students/templates/students/index.html
{% extends 'students/base.html' %}
{% load static %}
{% block content %}
<h3 class="m-4">All Students</h3>
<div class="row">
    <div class="col-12">
        {% if students %}
        <div class="card bg-light ms-4 me-4 mb-4">
            <div class="card-header">
            <i class="fa-solid fa-list fa-lg"></i> Students Records
            </div>
            <div class="card-body">
                <p class="card-text">
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                          <tr>
                            <th scope="col">Student Number</th>
                            <th scope="col">First Name</th>
                            <th scope="col">Last Name</th>
                            <th scope="col">Field of Study</th>
                            <th scope="col">GPA</th>
                            <th scope="col">Actions</th>
                            
                          </tr>
                        </thead>
                        <tbody>
                        {% for student in students %}
                          <tr>
                            <th scope="row">{{ student.student_number }}</th>
                            <td>{{ student.first_name }}</td>
                            <td>{{ student.last_name }}</td>
                            <td>{{ student.field_of_study }}</td>
                            <td>{{ student.gpa }}</td>
                            <td>
                               <button type="button" class="btn btn-success me-1" href="{% url 'students:view_student' student.id %}" data-bs-toggle="modal" data-bs-target="#myModal{{student.id}}">
                                <i class="fa-solid fa-circle-info fa-lg"> </i>
                               </button>
                               <a class="btn btn-warning me-1" href="{% url 'students:edit' student.id %}">
                                <i class="fa-solid fa-pen-to-square fa-lg"> </i> </a>
                                
                               <!-- Modal - View Student -->
                               <div class="modal" id="myModal{{student.id}}" tabindex="-1" aria-label="myModalLabel1" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title">
                                        Student: {{ student.first_name }} {{ student.last_name }}
                                      </h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true"></span>
                                      </button>
                                    </div>
                                    <div class="modal-body">
                                        <ul class="list-unstyled">
                                            <li>Student Number: <strong>{{ student.student_number }}</strong></li>
                                            <li>First Name: <strong>{{ student.first_name }}</strong></li>
                                            <li>Last Name: <strong>{{ student.last_name }}</strong></li>
                                            <li>E-mail: <strong>{{ student.email_address }}</strong></li>
                                            <li>Field of Study: <strong>{{ student.field_of_study }}</strong></li>
                                            <li>GPA: <strong>{{ student.gpa }}</strong></li>
                                            
                                        </ul>
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                                    </div>
                                    
                                  </div>
                                </div>
                              </div>
                              <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{student.id}}">
                                <i class="fa-solid fa-trash-can fa-lg"> </i>
                                </button>
                                <!-- Modal - Delete Student -->
                                <div class="modal" id="delete{{student.id}}" tabindex="-1" aria-label="myModalLabel2" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <h5 class="modal-title">
                                            Student: {{ student.first_name }} {{ student.last_name }}
                                          </h5>
                                          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true"></span>
                                          </button>
                                        </div>
                                        <div class="modal-body">
                                            <p>Are you sure you want to delete this student?</p>
                                        </div>
                                        <div class="modal-footer">
                                            <form action="{% url 'students:delete' student.id %}" method="POST">
                                                {% csrf_token %}
                                                <input type="submit" class="btn btn-primary" value="Delete">
                                            </form>
                                            
                                          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                        </div>
                                        
                                      </div>
                                    </div>
                                  </div>
                            </td>
                          </tr>
                        {% endfor %}
                          
                        </tbody>
                      </table>
                </div>
                
                </p>
            </div>
        </div>
        {% else %}
        <div class="alert alert-primary ms-4 me-4">
            No Students Found
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}